# Generated by Django 5.2.4 on 2026-07-21 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpotifyProfile',
        ),
    ]
