# Generated by Django 5.2.17 on 2026-08-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0012_submission_isrc"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="is_draft",
            field=models.BooleanField(
                default=False,
                help_text="Keep this round staff-only until it is saved or published.",
            ),
        ),
    ]
