# Generated by Django 5.2.17 on 2026-08-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0016_homepagecountdown_notificationblast"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationblast",
            name="sending_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
