from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import ensure_csrf_cookie

from . import views

urlpatterns = [
    path('health/', views.health, name='health'),
    path('service-worker.js', views.service_worker, name='service_worker'),
    path('', views.landing, name='landing'),
    path('signup/', views.signup, name='signup'),
    path('waiting-for-approval/', views.waiting_approval, name='waiting_approval'),
    path('terms/', views.terms, name='terms'),
    path('privacy/', views.privacy, name='privacy'),
    path('login/', never_cache(ensure_csrf_cookie(LoginView.as_view(template_name='league/login.html'))), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('home/', views.home, name='home'),
    path('round/<int:pk>/', views.round_detail, name='round_detail'),
    path('round/<int:pk>/songs/', views.song_picker, name='song_picker'),
    path('api/spotify/search/', views.spotify_search, name='spotify_search'),
    path('api/live/', views.live_status, name='live_status'),
    path('round/<int:pk>/submit/', views.submit_song, name='submit_song'),
    path('round/<int:pk>/vote/<int:submission_id>/', views.vote, name='vote'),
    path('round/<int:pk>/voting-complete/', views.voting_complete, name='voting_complete'),
    path('api/guides/voting-seen/', views.voting_guide_seen, name='voting_guide_seen'),
    path('api/submission-rules/accept/', views.accept_submission_rules, name='accept_submission_rules'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('stats/', views.stats, name='stats'),
    path('profile/edit/', views.profile_edit, name='profile_edit'),
    path('profile/picture/upload/', views.upload_profile_picture, name='profile_picture_upload'),
    path('profile/picture/remove/', views.remove_profile_picture, name='profile_picture_remove'),
    path('stats/<str:username>/', views.stats, name='user_stats'),
    path('archive/', views.archive, name='archive'),
    path('notifications/', views.notification_settings, name='notification_settings'),
    path('api/push/subscribe/', views.push_subscribe, name='push_subscribe'),
    path('api/push/unsubscribe/', views.push_unsubscribe, name='push_unsubscribe'),
    path('control/', views.control_panel, name='control_panel'),
    path('control/rounds/', views.control_rounds, name='control_rounds'),
    path('control/badges/', views.control_badges, name='control_badges'),
    path('control/users/', views.control_users, name='control_users'),
    path('control/seasons/new/', views.season_create, name='season_create'),
    path('api/seasons/<int:pk>/welcome-seen/', views.season_welcome_seen, name='season_welcome_seen'),
    path('control/badges/new/', views.badge_create, name='badge_create'),
    path('control/badges/<int:pk>/edit/', views.badge_edit, name='badge_edit'),
    path('control/badges/<int:badge_pk>/users/<int:user_pk>/toggle/', views.badge_award, name='badge_award'),
    path('control/rounds/new/', views.round_create, name='round_create'),
    path('control/rounds/<int:pk>/edit/', views.round_edit, name='round_edit'),
    path('control/rounds/<int:pk>/archive/', views.round_archive, name='round_archive'),
    path('control/rounds/<int:pk>/delete/', views.round_delete, name='round_delete'),
    path('control/seasons/<int:pk>/edit/', views.season_edit, name='season_edit'),
    path('control/users/<int:pk>/<str:action>/', views.user_action, name='user_action'),
    path('control/spotify/connect/', views.spotify_connect, name='spotify_connect'),
    path('control/spotify/callback/', views.spotify_callback, name='spotify_callback'),
    path('control/rounds/<int:pk>/playlist/', views.create_playlist, name='create_playlist'),
    path('control/rounds/<int:pk>/status/', views.round_status, name='round_status'),
    path('control/rounds/<int:pk>/<str:action>/', views.round_action, name='round_action'),
]
